### ISSUE TITLE
Can't inline a content with nokogiri because of "undefined method `each' for false:FalseClass"

### ISSUE THREAD

**Issue by keysen** [premailer/premailer#280]
Hello,

I found a content on my app where premailer was not able to inline the html. 
I give you the guilty html below: 
```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title>CW</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <style type="text/css">
      body {
        background-color: #E0E0E0;
      }
        color: #000;
      }
        color: #ff972F;
      }
  </style>
</head>
  <body style="color:#ffffff">
    <font face="Verdana, Arial, Helvetica, sans-serif" color="#969696" size="1"> ... BLA BLA BLA ... </font>
  </body>
</html>
```

Here the resulting stacktrace: 
```ruby
     # ruby-2.1.7/gems/premailer-1.8.6/lib/premailer/adapter/nokogiri.rb:43:in `block in to_inline_css'
     # ruby-2.1.7/gems/css_parser-1.3.7/lib/css_parser/parser.rb:192:in `block (2 levels) in each_selector'
     # gems/css_parser-1.3.7/lib/css_parser/rule_set.rb:90:in `block in each_selector'
     # ruby-2.1.7/gems/css_parser-1.3.7/lib/css_parser/rule_set.rb:90:in `each'
     # ruby-2.1.7/gems/css_parser-1.3.7/lib/css_parser/rule_set.rb:90:in `each_selector'
     # ruby-2.1.7/gems/css_parser-1.3.7/lib/css_parser/parser.rb:191:in `block in each_selector'
     # ruby-2.1.7/gems/css_parser-1.3.7/lib/css_parser/parser.rb:180:in `block in each_rule_set'
     # ruby-2.1.7/gems/css_parser-1.3.7/lib/css_parser/parser.rb:178:in `each'
     # ruby-2.1.7/gems/css_parser-1.3.7/lib/css_parser/parser.rb:178:in `each_rule_set'
     # ruby-2.1.7/gems/css_parser-1.3.7/lib/css_parser/parser.rb:190:in `each_selector'
     # ruby-2.1.7/gems/premailer-1.8.6/lib/premailer/adapter/nokogiri.rb:22:in `to_inline_css'
```

I know exactly why this bug is happening, it's because in my example when we do: 
```ruby
in: lib/premailer/adapter/nokogiri:43
doc.search(selector).each do |el|
```
The search method from nokogiri is returning a boolean instead of an array. I asked to nokogiri whether it's normal or not. I'm still waiting for an answer.

**Comment by keysen** [comment]
bump I had an answer from nokogiri [link to nokogiri issue](https://github.com/sparklemotion/nokogiri/issues/1414)

**Comment by flavorjones** [comment]
Good nokogiri practice is to not use `#search` unless you don't know whether the query will be CSS or XPath. Otherwise use `#css` or `#xpath`, since `#search` has to guess, and will guess wrongly on occasion (especially since "." is a valid leading character in either syntax).
