### ISSUE TITLE
ArgumentError: comparison of Fixnum with nil failed

### ISSUE THREAD

**Issue by ryanwjackson** [premailer/premailer#290]
It looks like there is an issue with inlining CSS.  We just updated our version (note CSS Parser hasn't been updated in some time).  The failure is `if @declarations[dest][:order] > @declarations[src][:order]` where `@declarations[src][:order]` is `nil`.

The `dest` is `"border-bottom-width"` and `src` is `"border-width"`.

Any clue?

Stack trace:

```
ArgumentError: comparison of Fixnum with nil failed
  from /Users/awesome/.rvm/gems/ruby-2.2.1/gems/css_parser-1.3.7/lib/css_parser/rule_set.rb:455:in `>'
  from /Users/awesome/.rvm/gems/ruby-2.2.1/gems/css_parser-1.3.7/lib/css_parser/rule_set.rb:455:in `split_declaration'
  from /Users/awesome/.rvm/gems/ruby-2.2.1/gems/css_parser-1.3.7/lib/css_parser/rule_set.rb:216:in `block in expand_dimensions_shorthand!'
  from /Users/awesome/.rvm/gems/ruby-2.2.1/gems/css_parser-1.3.7/lib/css_parser/rule_set.rb:180:in `each'
  from /Users/awesome/.rvm/gems/ruby-2.2.1/gems/css_parser-1.3.7/lib/css_parser/rule_set.rb:180:in `expand_dimensions_shorthand!'
  from /Users/awesome/.rvm/gems/ruby-2.2.1/gems/css_parser-1.3.7/lib/css_parser/rule_set.rb:127:in `expand_shorthand!'
  from /Users/awesome/.rvm/gems/ruby-2.2.1/gems/premailer-1.8.6/lib/premailer/adapter/nokogiri.rb:74:in `block in to_inline_css'
  from /Users/awesome/.rvm/gems/ruby-2.2.1/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:187:in `block in each'
  from /Users/awesome/.rvm/gems/ruby-2.2.1/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:186:in `upto'
  from /Users/awesome/.rvm/gems/ruby-2.2.1/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:186:in `each'
  from /Users/awesome/.rvm/gems/ruby-2.2.1/gems/premailer-1.8.6/lib/premailer/adapter/nokogiri.rb:63:in `to_inline_css'
  from /Users/awesome/.rvm/gems/ruby-2.2.1/gems/premailer-rails-1.9.0/lib/premailer/rails/hook.rb:75:in `generate_html_part'
  from /Users/awesome/.rvm/gems/ruby-2.2.1/gems/premailer-rails-1.9.0/lib/premailer/rails/hook.rb:63:in `generate_alternative_part'
  from /Users/awesome/.rvm/gems/ruby-2.2.1/gems/premailer-rails-1.9.0/lib/premailer/rails/hook.rb:50:in `generate_html_part_replacement'
  from /Users/awesome/.rvm/gems/ruby-2.2.1/gems/premailer-rails-1.9.0/lib/premailer/rails/hook.rb:24:in `perform'
  from /Users/awesome/.rvm/gems/ruby-2.2.1/gems/premailer-rails-1.9.0/lib/premailer/rails/hook.rb:8:in `perform'
... 17 levels...
  from /Users/awesome/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
  from /Users/awesome/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
  from /Users/awesome/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
  from /Users/awesome/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
  from /Users/awesome/.rvm/gems/ruby-2.2.1/gems/spring-1.3.6/lib/spring/commands/rails.rb:6:in `call'
  from /Users/awesome/.rvm/gems/ruby-2.2.1/gems/spring-1.3.6/lib/spring/command_wrapper.rb:38:in `call'
  from /Users/awesome/.rvm/gems/ruby-2.2.1/gems/spring-1.3.6/lib/spring/application.rb:183:in `block in serve'
  from /Users/awesome/.rvm/gems/ruby-2.2.1/gems/spring-1.3.6/lib/spring/application.rb:156:in `fork'
  from /Users/awesome/.rvm/gems/ruby-2.2.1/gems/spring-1.3.6/lib/spring/application.rb:156:in `serve'
  from /Users/awesome/.rvm/gems/ruby-2.2.1/gems/spring-1.3.6/lib/spring/application.rb:131:in `block in run'
  from /Users/awesome/.rvm/gems/ruby-2.2.1/gems/spring-1.3.6/lib/spring/application.rb:125:in `loop'
  from /Users/awesome/.rvm/gems/ruby-2.2.1/gems/spring-1.3.6/lib/spring/application.rb:125:in `run'
  from /Users/awesome/.rvm/gems/ruby-2.2.1/gems/spring-1.3.6/lib/spring/application/boot.rb:18:in `<top (required)>'
  from /Users/awesome/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  from /Users/awesome/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```

**Comment by cbillen** [comment]
We have the same issue on exactly the same attribute.  latest css parser and i narrowed it down to this rule

.prodeso-item-category .category {
    border-bottom: 3px solid #ffffff;
}

**Comment by akzhan** [comment]
Was fixed by css_parser gem.
