### ISSUE TITLE
#<NoMethodError: undefined method `>' for nil:NilClass>

### ISSUE THREAD

**Issue by sampatbadhe** [premailer/premailer#340]
I am getting an error `#<NoMethodError: undefined method `>' for nil:NilClass>` while sending an email.

backtrace :point_down:   
```
/projects/rails/emailapp/vendor/ruby/2.3.0/gems/css_parser-1.3.7/lib/css_parser/rule_set.rb:453:in `split_declaration'", 
"/projects/rails/emailapp/vendor/ruby/2.3.0/gems/css_parser-1.3.7/lib/css_parser/rule_set.rb:293:in `expand_list_style_shorthand!'", 
"/projects/rails/emailapp/vendor/ruby/2.3.0/gems/css_parser-1.3.7/lib/css_parser/rule_set.rb:130:in `expand_shorthand!'", 
"/projects/rails/emailapp/vendor/ruby/2.3.0/gems/premailer-1.8.6/lib/premailer/adapter/nokogiri.rb:74:in `block in to_inline_css'", 
"/projects/rails/emailapp/vendor/ruby/2.3.0/gems/nokogiri-1.6.8.1/lib/nokogiri/xml/node_set.rb:187:in `block in each'", 
"/projects/rails/emailapp/vendor/ruby/2.3.0/gems/nokogiri-1.6.8.1/lib/nokogiri/xml/node_set.rb:186:in `upto'", 
"/projects/rails/emailapp/vendor/ruby/2.3.0/gems/nokogiri-1.6.8.1/lib/nokogiri/xml/node_set.rb:186:in `each'", 
"/projects/rails/emailapp/vendor/ruby/2.3.0/gems/premailer-1.8.6/lib/premailer/adapter/nokogiri.rb:63:in `to_inline_css'", 
"/projects/rails/emailapp/vendor/ruby/2.3.0/gems/premailer-rails-1.9.0/lib/premailer/rails/hook.rb:75:in `generate_html_part'", 
"/projects/rails/emailapp/vendor/ruby/2.3.0/gems/premailer-rails-1.9.0/lib/premailer/rails/hook.rb:63:in `generate_alternative_part'", 
"/projects/rails/emailapp/vendor/ruby/2.3.0/gems/premailer-rails-1.9.0/lib/premailer/rails/hook.rb:50:in `generate_html_part_replacement'", 
"/projects/rails/emailapp/vendor/ruby/2.3.0/gems/premailer-rails-1.9.0/lib/premailer/rails/hook.rb:24:in `perform'", 
"/projects/rails/emailapp/vendor/ruby/2.3.0/gems/premailer-rails-1.9.0/lib/premailer/rails/hook.rb:8:in `perform'", 
"/projects/rails/emailapp/vendor/ruby/2.3.0/gems/mail-2.6.4/lib/mail/mail.rb:243:in `block in inform_interceptors'", 
"/projects/rails/emailapp/vendor/ruby/2.3.0/gems/mail-2.6.4/lib/mail/mail.rb:242:in `each'", 
"/projects/rails/emailapp/vendor/ruby/2.3.0/gems/mail-2.6.4/lib/mail/mail.rb:242:in `inform_interceptors'", 
"/projects/rails/emailapp/vendor/ruby/2.3.0/gems/mail-2.6.4/lib/mail/message.rb:225:in `inform_interceptors'", 
"/projects/rails/emailapp/vendor/ruby/2.3.0/gems/mail-2.6.4/lib/mail/message.rb:235:in `deliver'", 
"/projects/rails/emailapp/vendor/ruby/2.3.0/gems/actionmailer-4.2.5/lib/action_mailer/message_delivery.rb:85:in `deliver_now'", 
"/projects/rails/emailapp/vendor/ruby/2.3.0/gems/actionmailer-4.2.5/lib/action_mailer/message_delivery.rb:105:in `deliver'"
```

Any idea what content will cause this error?

**Comment by grosser** [comment]
open an issue in css_parser ?

**Comment by grosser** [comment]
... also bump css_parser to latest ... come back if it's still an issue then :D

**Comment by sampatbadhe** [comment]
Updating Gem it works fine thanks @grosser 👍
