### ISSUE TITLE
rule_set_exceptions option isn't respected in the nokogiri* adapters

### ISSUE THREAD

**Issue by rlr** [premailer/premailer#420]
The adapters seem to all initialize `CssParser` without passing in any options.

If I create a mail message with `body = '<div style="margin: 0px 0px 10px !important 0px;">INVALID CSS</div>'` Then `Premailer::Rails::Hook.perform(mail)` blows up even if I set `rule_set_exceptions: false`

```
     Failure/Error: Premailer::Rails::Hook.perform(mail)

     ArgumentError:
       Cannot parse 0px 0px 10px ! 0px
     # /Users/rlr/.rvm/gems/ruby-2.7.4/gems/css_parser-1.12.0/lib/css_parser/rule_set.rb:378:in `block in expand_dimensions_shorthand!'
     # /Users/rlr/.rvm/gems/ruby-2.7.4/gems/css_parser-1.12.0/lib/css_parser/rule_set.rb:353:in `each'
     # /Users/rlr/.rvm/gems/ruby-2.7.4/gems/css_parser-1.12.0/lib/css_parser/rule_set.rb:353:in `expand_dimensions_shorthand!'
     # /Users/rlr/.rvm/gems/ruby-2.7.4/gems/css_parser-1.12.0/lib/css_parser/rule_set.rb:294:in `expand_shorthand!'
     # /Users/rlr/.rvm/gems/ruby-2.7.4/gems/css_parser-1.12.0/lib/css_parser.rb:71:in `block in merge'
     # /Users/rlr/.rvm/gems/ruby-2.7.4/gems/css_parser-1.12.0/lib/css_parser.rb:70:in `each'
     # /Users/rlr/.rvm/gems/ruby-2.7.4/gems/css_parser-1.12.0/lib/css_parser.rb:70:in `merge'
     # /Users/rlr/.rvm/gems/ruby-2.7.4/gems/premailer-1.17.0/lib/premailer/adapter/nokogiri.rb:71:in `block in to_inline_css'
     # /Users/rlr/.rvm/gems/ruby-2.7.4/gems/nokogiri-1.13.8/lib/nokogiri/xml/node_set.rb:234:in `block in each'
     # /Users/rlr/.rvm/gems/ruby-2.7.4/gems/nokogiri-1.13.8/lib/nokogiri/xml/node_set.rb:233:in `upto'
     # /Users/rlr/.rvm/gems/ruby-2.7.4/gems/nokogiri-1.13.8/lib/nokogiri/xml/node_set.rb:233:in `each'
     # /Users/rlr/.rvm/gems/ruby-2.7.4/gems/premailer-1.17.0/lib/premailer/adapter/nokogiri.rb:61:in `to_inline_css'
     # ./config/initializers/premailer_rails.rb:10:in `generate_html_part'
     # /Users/rlr/.rvm/gems/ruby-2.7.4/bundler/gems/premailer-rails-2870060f9740/lib/premailer/rails/hook.rb:52:in `generate_html_part_replacement'
     # /Users/rlr/.rvm/gems/ruby-2.7.4/bundler/gems/premailer-rails-2870060f9740/lib/premailer/rails/hook.rb:24:in `perform'
     # /Users/rlr/.rvm/gems/ruby-2.7.4/bundler/gems/premailer-rails-2870060f9740/lib/premailer/rails/hook.rb:8:in `perform'
```

**Comment by grosser** [comment]
can you make a PR to fix this ?
